### ISSUE TITLE
[Follow up from Steam] Is there something wrong, or the is the plugin outdated?

### ISSUE THREAD

**Issue by InsigniaX** [Ryzhehvost/ASF-Achievement-Manager#11]
Anyways, thanks for all the help in the Archi group and here is my final question everything up and working for the past day! Domain ready, everything perfect, just wanna say thanks and I got one last question. How would I enable this plugin? I keep getting a error and wont show up in plugins. Here's the log https://pastebin.com/JhsCq0wS Plugin I'm trying to install is ASF-Achievement-Manager by Ryzhehvost (you which i didnt know)

**Comment by Ryzhehvost** [comment]
Yes, this plugin is outdated and does not work with latest ASF. I plan to update it when I will have some time, but there is no estimated date.

**Comment by Ryzhehvost** [comment]
closed with #12
