### ISSUE TITLE
Is it possible to add statistical modification For example: total_time_played?

### ISSUE THREAD

**Issue by icebound97** [Ryzhehvost/ASF-Achievement-Manager#16]
Is it possible to add statistical modification
For example: total_time_played
![1111](https://user-images.githubusercontent.com/28422863/125054985-5ac02900-e0d9-11eb-9249-f11f17b65ce5.png)

**Comment by Ryzhehvost** [comment]
Or course technically it's possible, and you know it. It's just that I'm not really interested in implementing such functionality. If you feel like it - you are welcome to implement it and send a PR.
