### ISSUE TITLE
Console friendly symbols

### ISSUE THREAD

**Issue by AndhikaWB** [Ryzhehvost/ASF-Achievement-Manager#17]
Could you replace the ✅, ❌, and ⚠️ symbol with simple characters (e.g. O for ✅, X for ❌, S for ⚠️) when the command is run from ASF directly? Current version will show ⍰ character instead.
![image](https://user-images.githubusercontent.com/17119394/125171822-811cbc00-e1e0-11eb-8fa4-ea7f7b6067e8.png)

**Comment by Ryzhehvost** [comment]
Then start using some console that isn't shit.
Putty:
![изображение](https://user-images.githubusercontent.com/15903022/125174608-465e5800-e1cf-11eb-95fb-cea39c2f9a23.png)
Windows (Conemu):
![изображение](https://user-images.githubusercontent.com/15903022/125175023-22e8dc80-e1d2-11eb-9f03-e1ade76b60e7.png)
Windows (Windows termianl)
![изображение](https://user-images.githubusercontent.com/15903022/125175305-de5e4080-e1d3-11eb-9755-328a5ce67738.png)

**Comment by AndhikaWB** [comment]
Thanks for the suggestion.
