### ISSUE TITLE
Add a new function

### ISSUE THREAD

**Issue by fabioganga1** [Ryzhehvost/ASF-Achievement-Manager#18]
You cannot add a function where every second that passes will unlock a feat randomly, so it will look more real.

**Comment by Ryzhehvost** [comment]
I'm not interested in coding such feature, because I don't care if unlocked achievements look "more real" or not. You are welcome to make a fork of plugin and implement it yourself. Also, if you want, I can create a personal version of plugin just for you for about $200.
