### ISSUE TITLE
[Request] Legit automated Unlocks

### ISSUE THREAD

**Issue by Exadious** [Ryzhehvost/ASF-Achievement-Manager#23]
Games entered at "GamesPlayedWhileIdle" should get the possibility to unlock the achievements automatically.

As an additional option it would be nice if a random factor to unlock the achievements. 

Also it would be good if not all achievements are unlocked at once but spread over a certain time.
For example every 25 minutes or different time spans (random = first achievement after 3 minutes, the second after 10, the third after 7 etc.).

**Comment by woctezuma** [comment]
I think this is out of the scope of this project. The project is similar to SAM: it allows to manually manage achievements (list, lock, unlock). However, what you suggest is an additional feature to obfuscate an **automatic** unlocking of achievements by unlocking some of them **at random times** while idling.

**Comment by Ryzhehvost** [comment]
As @woctezuma already said, it's out of scope of this plugin. You can fork it and add your features, or you can make another plugin that will just call commands from this plugin, or you can even make a simple script that will send commands to ASF via IPC. It's all up to you. But I'm not going to add any automation for achievements, unless you are willing to pay for this.
