### ISSUE TITLE
Poor functionality

### ISSUE THREAD

**Issue by Botan626** [Ryzhehvost/ASF-Achievement-Manager#4]
Commands, which will allow to perform following actions are strongly needed:

1. List all games with locked achievements with appIDs, with the choice of listing order, 

2. Unlock all available achievements for the current bot throughout all games.

**Comment by Ryzhehvost** [comment]
Sounds too niche for me. First suggestion even falls sounds at least reasonable, achievement hunters may like it , but there are already services for that, so I see no reason to re-invent the wheel. And unlocking all available achievements sounds totally overkill. Not going to implement, feel free to send PR for first part if you feel like it.
