### ISSUE TITLE
is it possible to add a command to change the state of steam account like SAM

### ISSUE THREAD

**Issue by jackma92** [Ryzhehvost/ASF-Achievement-Manager#7]
Just like  “stateset gameid state value” to set the state of account

**Comment by Ryzhehvost** [comment]
What do you mean by "state" of account? Could you please elaborate?

**Comment by jackma92** [comment]
for example: sam could change the time this account played in cs:go 
![Uploading 0605C265-2A00-4B75-903F-CFA0F52A3303.jpeg…](1)

**Comment by Ryzhehvost** [comment]
You can "play" custom games in ASF without help of this plugin.
