### ISSUE TITLE
Permission bug?

### ISSUE THREAD

**Issue by blakebill** [Ryzhehvost/ASF-Achievement-Manager#8]
There’re 3 bots in my asf.
A bot is owner.
B bot is used for commands control.
C bot is master.
If use A bot send `!alist Cbot appid` to b that b bot will respond but if I use c bot to send the same command the bot never respond. I view the debug log but I have no idea about it.

**Comment by Ryzhehvost** [comment]
Is the C bot set as master of itself? Because if not then it's working as intended, other ASF commands won't work too.

**Comment by blakebill** [comment]
> Is the C bot set as master of itself? Because if not then it's working as intended, other ASF commands won't work too.

I have set this, and other asf commands such as `!level cbot` will respond me.

I extracted the log and edit the bots name. I hope its useful to you!

A: https://drive.google.com/file/d/183DbIe2JUBIwC6rKBiLMOEFXhbekg6Hd/view?usp=sharing
C: https://drive.google.com/file/d/1UFEyHCQQN57eF2xODsSl4u_LdSEGknnj/view?usp=sharing

**Comment by Ryzhehvost** [comment]
Please don't post publicly logs in debug mode (why do you even enabled it?). I removed links from your comment for security. What would really help me to reproduce issue is configs of your bots, of course remove loging and passwords first (and any other sensitive information that may be present there, like parental pin code, etc).

**Comment by blakebill** [comment]
Got it!
This is bots' config: [Google Drive](https://drive.google.com/file/d/1Eech3udC1J8AVt7AQG3t1DkOnL9gkzzX/view?usp=sharing)

**Comment by Ryzhehvost** [comment]
Fixed in 0.1.2.0, thank you for report! 👍
