### ISSUE TITLE
ASFversion4.2.0.1 can't use

### ISSUE THREAD

**Issue by Gensokyo1995** [Ryzhehvost/ASF-Achievement-Manager#9]
ASF update to 4.2.0.1,i cant't use this plugin,!alist and !aset all make bot ont online.After i send instructions to bot,saf return Can't retrieve achievements for appid.
Is it my problem?or you need update plugin?

**Comment by Ryzhehvost** [comment]
Fixed in 0.1.2.0, thank you for report!
